# Generated by Django 5.2 on 2025-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mcqquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='purchase_courses',
            field=models.ManyToManyField(blank=True, to='myapp.course'),
        ),
    ]
