# Generated by Django 5.2 on 2025-04-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf_material',
            field=models.TextField(blank=True, null=True),
        ),
    ]
