# Generated by Django 5.2 on 2025-04-23 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_lessontestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontestresult',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_test_results', to='myapp.course'),
            preserve_default=False,
        ),
    ]
