# Generated by Django 5.2 on 2025-04-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
