# Generated by Django 5.2 on 2025-04-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='pdf_file',
            new_name='pdf_files',
        ),
    ]
