# Generated by Django 5.2 on 2025-04-25 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_pdf_file_certificate_pdf_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_completion', models.DateField(auto_now_add=True)),
                ('pdf_files', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userregister')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
